from gamingbench.games.tic_tac_toe import TicTacToe
from gamingbench.games.connect_four import ConnectFour
from gamingbench.games.breakthrough import Breakthrough
from gamingbench.games.first_sealed_auction import FirstSealedAuction
from gamingbench.games.liars_dice import LiarsDice
from gamingbench.games.negotiation import Negotiation
from gamingbench.games.nim import Nim
from gamingbench.games.pig import Pig
from gamingbench.games.kuhn_poker import KuhnPoker
from gamingbench.games.prisoners_dilemma import PrisonersDilemma
from gamingbench.games.cooperative_negotiation import CooperativeNegotiation
from gamingbench.games.hanabi import Hanabi
from gamingbench.games.texas_holdem import TexasHoldem
from gamingbench.games.mmlu_pro_qa import MmluProQA
