
def _construct_head_prompt():
    return 'You are playing MMLUPRO QA, a single-player game based on the Hub-and-Spoke architecture. ' \
           'Your goal is to answer a multiple-choice question from the MMLU Pro dataset. ' \
           'To assist you, you will be provided with the answers and reasoning generated by several specialized "Spoke" agents (e.g., Spoke 1, Spoke 2). ' \
           'You must synthesize their peer answers and use your own reasoning to choose the correct final answer. ' \
           'If you choose the correct answer, you score 1.0 (win). If you are incorrect, you score 0.0 (loss). ' \
           'You must select one of the available options. Each action is represented by <x> where x refers to the chosen option letter, e.g. <A> or <B>.'


def construct_observation_prompt(observations):
    board = observations.get('board', '')
    legal_moves = observations.get('legal_moves', [])
    legal_move_str = ', '.join(legal_moves)
    
    prompt = f'Here is the question and the Spoke peer answers:\n\n{board}\n\n'
    prompt += f'The legal actions are: {legal_move_str}.'
    
    return prompt

def _construct_game_history_legend():
    return '[Position Legend] Each [Position] line shows the question, options, and peer answers.\n' \
           'Format: Question text followed by peer reasoning.\n' \
           '[Move] lines show the final action taken by you.\n\n'
